language: node_js
node_js:
  - "10.15.3"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - yes | npm install -g @angular/cli
script:
- ng build --prod --base-href https://github.com/rdnovell/desapp-groupL-frontend

deploy:
  provider: heroku
  api_key:
    secure: "JtvfJ0zNNPx6CTMJFkryR1QJ24eVqcA6/MW72szXdooqEVQcAtddnbWrhIr1hlQi2OqSyvyY8tAeWwV6OHzEL7wO1/AbguXjlHpbZ5b26ucS5jxZeB427Hu0MdLJmoVWpqqUOE3XU/BWjDNWVRVF9ooxxCqy7C47tvIZOTFz15sZKPUeL6LGS88v7lpuNy6xv60DS0u/r28znWUrBB4T0E77Ws2Hif3mh74XC5ydiaDFK71u0NgYw9W9yEKF90KgtaFG04dMyJfok1L0zd0iSrNGz9RVGlySn6B6l3lozYcKAqmjkOnvuH8p6ogpKHcOwiXSpC+gOl2xZjANvA3bhvtOvLHM2QvmIhaPtOS+Hog6GvGu6fwrB0iNhfqP2Bug3zC1iPYnUK51nXxZp/I8FkIgN8uU3IZiZfh42ENynXgXJxckyo0opV8OWdJ7009Uf3SJw3zfiYQ9HhV0cSnr6CEizFWateeB7OaMXDRl3Zx6HM4qhfBJjhWmxTJuxtYfdUcOV8w7W1Z0h04rLxVb/hUlQa4YulMB+fvi4QNqOBaqwlU9/48j07su0V658ojXM+5/xYj9xVqMsxMjyU4CFXvzwmN9JePd96sG9+8GwIyLN4N3YhVHSD4+6rXE/+wYxWxUMXpbJx45ITkMfd3Fx3OIbOpHXUm9IX++X4GmimM="
  app: eventeando-grupol
  on: master
